### ISSUE TITLE
Incorrect font filename - 'graffiti' should be 'Graffiti'

### ISSUE THREAD

**Issue by JaredBoone** [ship-components/ship-components-banner#4]
I'm building an app that depends on ship-components-banner and I'm seeing this error:

`error	15-Dec-2017 15:36:12	fs.js:646
error	15-Dec-2017 15:36:12	  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
error	15-Dec-2017 15:36:12	                 ^
error	15-Dec-2017 15:36:12	
error	15-Dec-2017 15:36:12	Error: ENOENT: no such file or directory, open '/{snip}/node_modules/figlet/lib/../fonts/graffiti.flf'
error	15-Dec-2017 15:36:12	    at Object.fs.openSync (fs.js:646:18)
error	15-Dec-2017 15:36:12	    at Object.fs.readFileSync (fs.js:551:33)
error	15-Dec-2017 15:36:12	    at Function.figlet.loadFontSync (/{snip}/node_modules/figlet/lib/node-figlet.js:38:23)
error	15-Dec-2017 15:36:12	    at Function.me.textSync (/{snip}/node_modules/figlet/lib/figlet.js:732:43)
error	15-Dec-2017 15:36:12	    at PackageBanner._constructLines (/{snip}/node_modules/ship-components-banner/lib/index.js:80:20)
error	15-Dec-2017 15:36:12	    at PackageBanner.build (/{snip}/node_modules/ship-components-banner/lib/index.js:99:20)`

Note - I'm building on linux x64, so fsevents is not available.

**Comment by JaredBoone** [comment]
confirmed this was working, fixed with PR #5
